packages:
  - packages/*
allowBuilds:
  '@bufbuild/buf': true
  canvas: true
  esbuild: true
  protobufjs: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
  - mongodb-memory-server
  - redis-memory-server
  - sharp
  # - simple-git-hooks
  - unrs-resolver
  - '@bufbuild/buf'
  - canvas
  - core-js
  - protobufjs
