name: Publish @danuni/dan-any
on:
  push:
    branches:
      - master
    paths:
      - 'packages/dan-any/package.json'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: |
          pnpm install --frozen-lockfile
      - name: Build @danuni/dan-any
        run: |
          cd ${{ github.workspace }}
          cd ./packages/dan-any/
          pnpx conventional-changelog-cli -p angular -i CHANGELOG.md -s
          pnpm run lint
          pnpm run build
          pnpm run test
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/packages/dan-any/CHANGELOG.txt
