name: Publish @dan-uni/dan-any-plugin-detaolu
on:
  push:
    tags:
      - 'dan-any-plugin-detaolu@*.*.*'
    paths:
      - packages/dan-any-plugin-detaolu/package.json
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm publish
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm modules
        uses: actions/cache@v4
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: |
          sudo apt-get update
          sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          pnpm install --frozen-lockfile

      - name: Build @danuni/dan-any-plugin-detaolu
        run: |
          cd ${{ github.workspace }}
          cd ./packages/dan-any-plugin-detaolu/
          # pnpx conventional-changelog-cli -p angular -i CHANGELOG.md -s
          pnpm run lint
          pnpm run build
          pnpm run test

      - name: Publish @danuni/dan-any-plugin-detaolu
        run: |
          cd ${{ github.workspace }}
          cd ./packages/dan-any-plugin-detaolu/
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
