name: Publish @dan-uni/dan-any
on:
  push:
    tags:
      - 'dan-any@*.*.*'
    paths:
      - 'packages/dan-any/package.json'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'npm publish'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm modules
        uses: actions/cache@v4
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: |
          pnpm install --frozen-lockfile

      - name: Build @danuni/dan-any
        run: |
          cd ${{ github.workspace }}
          cd ./packages/dan-any/
          # pnpx conventional-changelog-cli -p angular -i CHANGELOG.md -s
          pnpm run lint
          pnpm run build
          pnpm run test

      - name: Publish @danuni/dan-any
        run: |
          cd ${{ github.workspace }}
          cd ./packages/dan-any/
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
